Repository naman5825/Dsa_in_c, pull requests merged in 2022-10, with the labels that each got.

#2 linear search program added
  linear_search.c
Labels: hacktoberfest-accepted

#5 add this file
  binary_search.c
Labels: hacktoberfest, hacktoberfest-accepted

#10 pls adding this file.
  bubble_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#12 pls add this file
  sum_of_digit.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#16 Create reverse_ll.c
  reverse_ll.c
Labels: hacktoberfest, hacktoberfest-accepted

#21 pls add this file
  sumofarray.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
